name: Release

on:
  push:
    branches:
      - main
      - beta

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: 16.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build:prod
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
